import { getDb, newId, nowIso } from "@/lib/db";
import { countMemories, countMemoriesSince } from "@/lib/repo/memories";

// reasoning is optional on read (older rows generated before this field was
// added simply won't have it -- parseSuggestedRoles below defaults it to
// null rather than dropping the whole role) but always populated by every
// NEW generation (see generateSuggestedRoles in lib/ai.ts).
export type SuggestedRole = { title: string; industry: string | null; reasoning?: string | null };

export type SuggestedRolesRow = {
  id: string;
  user_id: string;
  roles_json: string;
  memory_count_at_generation: number;
  created_at: string;
  // One overall seniority band for the person (from the closed
  // OPPORTUNITY_SENIORITY_LIST in lib/config.ts), generated in the same
  // call as roles_json -- see generateSuggestedRoles' own comment in
  // lib/ai.ts. Null for rows generated before this existed, or whenever
  // the sample genuinely didn't support a confident read.
  overall_seniority: string | null;
};

// Below this many total memories there just isn't enough real evidence to
// name specific roles without guessing -- set a notch above Career
// Wrapped's own "full analysis" gate (CAREER_WRAPPED_THRESHOLDS.
// minForFullAnalysis = 5 in lib/careerWrapped.ts) since a named job title
// (plus an industry claim) is a much more concrete, checkable statement
// than a muscle-strength count.
//
// Exported (not just a local const) because lib/opportunities.ts reuses it
// as the same "personalize or show the generic nudge instead" gate for the
// Opportunities tab -- deliberately the SAME number rather than a second
// tuned threshold, since both features are really asking the identical
// question ("do we know this person well enough yet") and drifting them
// apart would just make Strivo's own behavior harder to reason about.
export const MIN_TOTAL_MEMORIES = 6;

// Same "enough new material, or enough time plus a little new material"
// re-trigger shape as growth narratives (see growthNarratives.ts) --
// deliberately kept at the same numbers, since this is generated by the
// exact same monthly automation run (see app/api/growth-narrative/run) and
// there's no reason for the two features to drift onto different cadences
// without a specific reason to.
const MIN_NEW_MEMORIES_FOR_RETRIGGER = 8;
const MIN_DAYS_FOR_RETRIGGER = 30;
const MIN_NEW_MEMORIES_IF_TIME_ELAPSED = 3;

export function createSuggestedRoles(input: {
  userId: string;
  roles: SuggestedRole[];
  memoryCountAtGeneration: number;
  overallSeniority: string | null;
}): SuggestedRolesRow {
  const db = getDb();
  const id = newId("roles");
  const ts = nowIso();
  db.prepare(
    `INSERT INTO suggested_roles (id, user_id, roles_json, memory_count_at_generation, created_at, overall_seniority)
     VALUES (?, ?, ?, ?, ?, ?)`
  ).run(id, input.userId, JSON.stringify(input.roles), input.memoryCountAtGeneration, ts, input.overallSeniority);
  return db.prepare(`SELECT * FROM suggested_roles WHERE id = ?`).get(id) as SuggestedRolesRow;
}

// IMPORTANT: scoped by user_id, same invariant as every other repo read in
// this app.
export function getLatestSuggestedRoles(userId: string): SuggestedRolesRow | undefined {
  const db = getDb();
  return db
    .prepare(`SELECT * FROM suggested_roles WHERE user_id = ? ORDER BY created_at DESC LIMIT 1`)
    .get(userId) as SuggestedRolesRow | undefined;
}

function parseSuggestedRoles(row: SuggestedRolesRow): SuggestedRole[] {
  try {
    const parsed = JSON.parse(row.roles_json);
    if (!Array.isArray(parsed)) return [];
    return parsed
      .filter(
        (r): r is SuggestedRole =>
          !!r && typeof r === "object" && typeof (r as SuggestedRole).title === "string" &&
          ((r as SuggestedRole).industry === null || typeof (r as SuggestedRole).industry === "string")
      )
      .map((r) => ({
        title: r.title,
        industry: r.industry,
        reasoning: typeof r.reasoning === "string" ? r.reasoning : null,
      }));
  } catch {
    return [];
  }
}

// No visibility-window gate the way the recap/growth/benchmark teasers get
// on Home (RECAP_VISIBLE_MS etc. in home/page.tsx) -- this just reads
// whatever the latest generation produced and shows it, the same
// "always-on reflection" treatment Career Wrapped gets rather than a
// time-boxed digest teaser. Returns null when nothing has ever been
// generated for this user yet (new account, or not enough history) so the
// caller can render an honest "still taking shape" state instead of an
// empty list.
export function getLatestSuggestedRolesForUser(
  userId: string
): { roles: SuggestedRole[]; generatedAt: string; seniority: string | null } | null {
  const row = getLatestSuggestedRoles(userId);
  if (!row) return null;
  const roles = parseSuggestedRoles(row);
  if (roles.length === 0) return null;
  return { roles, generatedAt: row.created_at, seniority: row.overall_seniority ?? null };
}

// Decides whether this user is due for a fresh round of role suggestions --
// called by the same monthly automation that decides growth-narrative
// eligibility (see app/api/growth-narrative/run), as a cheap pre-filter
// before spending an AI call on them. See the threshold constants above for
// the reasoning behind each check.
export function shouldGenerateSuggestedRoles(userId: string): boolean {
  const total = countMemories(userId);
  if (total < MIN_TOTAL_MEMORIES) return false;

  const latest = getLatestSuggestedRoles(userId);
  if (!latest) return true;

  const newSinceLast = countMemoriesSince(userId, latest.created_at);
  if (newSinceLast >= MIN_NEW_MEMORIES_FOR_RETRIGGER) return true;

  const daysSinceLast = (Date.now() - new Date(latest.created_at).getTime()) / (24 * 60 * 60 * 1000);
  if (daysSinceLast >= MIN_DAYS_FOR_RETRIGGER && newSinceLast >= MIN_NEW_MEMORIES_IF_TIME_ELAPSED) return true;

  return false;
}
